# -*- coding: utf-8 -*-
"""Nato alphabet project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sb5VhCiUgVJXuNdCv1kLhsAzDrJR5by1
"""

alphabet_meaning = {
    "A": "Ambition – Always dream big",
    "B": "Believe – Trust yourself",
    "C": "Courage – Face fears",
    "D": "Determination – Never give up",
    "E": "Energy – Stay positive",
    "F": "Focus – Concentrate on goals",
    "G": "Growth – Improve daily",
    "H": "Hope – Keep faith alive",
    "I": "Inspire – Motivate others",
    "J": "Joy – Be happy",
    "K": "Kindness – Be good to all",
    "L": "Learn – Gain knowledge",
    "M": "Hard Work – मेहनत करो",
    "N": "Never quit – Stay strong",
    "O": "Opportunity – Use chances",
    "P": "Patience – Wait and trust",
    "Q": "Quality – Do your best",
    "R": "Respect – Value everyone",
    "S": "Success – Achieve goals",
    "T": "Trust – Believe in process",
    "U": "Unity – Stay together",
    "V": "Victory – Win with effort",
    "W": "Wisdom – Think smart",
    "X": "eXcellence – Be your best",
    "Y": "Yes mindset – Stay positive",
    "Z": "Zeal – Full passion"
}

name = input("Enter your name: ")

print("\n✨ Your Meaningful Alphabet Message ✨\n")

for letter in name.upper():
    if letter in alphabet_meaning:
        print(f"{letter} : {alphabet_meaning[letter]}")